### ISSUE TITLE
Severe bug: Wrong disassembly 

### ISSUE THREAD

**Issue by Elmue** [esaulenka/Ghidra_C166#10]
These two disassemblies
`f2 fe ae f7        mov   r14, 0x37ae`
and
`e6 fc 00 80      mov   r12, 0x8000`
seem to load a constant value into a register in the Ghidra disassembly.

But they do completely different things.

The Infineon "Instruction Set Manual for the C166 Family" says on page 30
F2 MOV reg, mem
E6 MOV reg, #data16

This must urgently be fixed into the correct display:
`f2 fe ae f7        mov   r14, [0x37ae]`
and
`e6 fc 00 80      mov   r12, #0x8000`

otherwise the disassembly is unreadable.

**Comment by esaulenka** [comment]
@Elmue, thanks for report.

For unknown reason ghidra omit symbol `#` in my scpecification. I redid this in https://github.com/esaulenka/Ghidra_C166/commit/c64dd2a5e5b6132ba6f38d0b1293e7cfe684fb2a

But `MOV mem` instructions I leave unchanged, it is correct.
To improve memory references display, you should set correct values to DPPx registers. To do this, select code (or even whole memory) and press Ctrl-R.

**Comment by Elmue** [comment]
Now it is worse than before.
I loaded your new files and deleted the old SLA file and now tried to decompile the same file as before.
Result:

java.lang.NullPointerException
	at ghidra.program.database.symbol.SymbolManager.getPrimarySymbol(SymbolManager.java:1100)
	at ghidra.program.database.function.FunctionManagerDB.getFunctionAt(FunctionManagerDB.java:629)
	at ghidra.program.disassemble.Disassembler.isNoReturnCall(Disassembler.java:1347)
	at ghidra.program.disassemble.Disassembler.processInstructionFlows(Disassembler.java:1210)
	at ghidra.program.disassemble.Disassembler.processInstruction(Disassembler.java:1173)
	at ghidra.program.disassemble.Disassembler.disassembleInstructionBlock(Disassembler.java:1043)
	at ghidra.program.disassemble.Disassembler.disassembleNextInstructionSet(Disassembler.java:677)
	at ghidra.program.disassemble.Disassembler.disassemble(Disassembler.java:617)
	at ghidra.program.disassemble.Disassembler.disassemble(Disassembler.java:489)
	at ghidra.app.cmd.disassemble.DisassembleCommand.doDisassemblySeeds(DisassembleCommand.java:322)
	at ghidra.app.cmd.disassemble.DisassembleCommand.doDisassembly(DisassembleCommand.java:287)
	at ghidra.app.cmd.disassemble.DisassembleCommand.applyTo(DisassembleCommand.java:150)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:102)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:315)
	at java.base/java.lang.Thread.run(Thread.java:834)
